[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "cd CFM56-7B_WebApp && pip install -r requirements.txt"
]

[start]
cmd = "cd CFM56-7B_WebApp && gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120"

[variables]
PYTHONUNBUFFERED = "1"
